version: "3"
services:
  database:
    image: postgres:15.2-alpine
    container_name: schwarzdb_test
    ports:
      - "127.0.0.1:5435:5432"
    environment:
      POSTGRES_USER: schwarz_svc
      POSTGRES_PASSWORD: schwarz_svc
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: schwarz_svc
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U schwarz_svc -d schwarz_svc"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
